//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_BAOCAO
    {
        public string BAOCAO { get; set; }
        public string TENBAOCAO { get; set; }
        public string THAMSO { get; set; }
        public string GHICHU { get; set; }
        public string NHOMBAOCAO { get; set; }
        public string TENFILE { get; set; }
        public Nullable<bool> SHOW { get; set; }
        public Nullable<bool> NGAY { get; set; }
    }
}
