//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_HETHONG
    {
        public int ID { get; set; }
        public string COQUANCHUQUAN { get; set; }
        public string TENCOQUAN { get; set; }
        public string TENCOQUAN2 { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string FAX { get; set; }
        public string MAIL { get; set; }
        public string WEBSITE { get; set; }
        public string DIADIEM { get; set; }
        public string SMTPSERVER { get; set; }
        public string PATHSERVER { get; set; }
        public byte[] LOGO { get; set; }
        public Nullable<int> PERSECOND { get; set; }
        public Nullable<int> COMPORT { get; set; }
        public string URLHINH { get; set; }
        public Nullable<int> I_Width { get; set; }
        public Nullable<int> I_Height { get; set; }
        public Nullable<int> I_Quality { get; set; }
        public Nullable<int> SaiSoViTri { get; set; }
        public Nullable<bool> IsCheckIn { get; set; }
        public string PathDMS { get; set; }
        public string PathCRM { get; set; }
        public Nullable<int> NguoiTuyenMoi { get; set; }
        public Nullable<int> NguoiTuyenThayThe { get; set; }
        public Nullable<bool> IsCheckOut { get; set; }
        public Nullable<int> MaxGetLocation { get; set; }
        public string MailTitleNghiPhep { get; set; }
        public string MailTitleXNC { get; set; }
        public string MailTitleTC { get; set; }
        public string MailTitleCT { get; set; }
    }
}
