//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NGONNGU
    {
        public int NGONNGU { get; set; }
        public string MANGONNGU { get; set; }
        public string TENNGONNGU { get; set; }
        public Nullable<bool> ISHIENTHI { get; set; }
    }
}
