//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NHATKY
    {
        public int NHATKY { get; set; }
        public string TENMAY { get; set; }
        public string TAIKHOAN { get; set; }
        public System.DateTime BATDAU { get; set; }
        public System.DateTime KETTHUC { get; set; }
        public string GHICHU { get; set; }
    }
}
