//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_SQL_CAU_LENH
    {
        public string MaNhom { get; set; }
        public string MaCauLenh { get; set; }
        public string MoTa { get; set; }
        public string SqlRun { get; set; }
        public string SqlDoc { get; set; }
    }
}
