//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_NhatkyLoi
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string TaiKhoan { get; set; }
        public string Loi { get; set; }
        public string LoaiChucNang { get; set; }
        public string NoiDung { get; set; }
    }
}
