//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_NghiBuChiTiet
    {
        public long IDNghiPhep { get; set; }
        public string IDTangCa { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayPhatSinh { get; set; }
        public Nullable<int> SoPhut { get; set; }
        public bool Del { get; set; }
        public Nullable<int> NguoiDel { get; set; }
        public Nullable<System.DateTime> NgayDel { get; set; }
    }
}
