//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_XacNhanCong
    {
        public long IDXacNhanCong { get; set; }
        public int NhanSu { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public Nullable<bool> GioVao { get; set; }
        public string NguyenNhan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string MayTao { get; set; }
        public string MaTrangThaiDuyet { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<int> IDNguoiDuyetKeTiep { get; set; }
        public Nullable<bool> Block { get; set; }
        public Nullable<System.DateTime> NgayBlock { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<int> NguoiThayDoiLanCuoi { get; set; }
        public Nullable<System.DateTime> NgayThayDoiLanCuoi { get; set; }
        public Nullable<int> NguoiTuChoi { get; set; }
        public Nullable<System.DateTime> NgayTuChoi { get; set; }
        public Nullable<bool> XacNhanCong { get; set; }
        public Nullable<bool> CaDem { get; set; }
    }
}
