//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CongNgay
    {
        public System.DateTime Date { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string MaChamCong { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<System.TimeSpan> GioVaoChuan { get; set; }
        public Nullable<System.TimeSpan> GioRaChuan { get; set; }
        public Nullable<double> GioQuyDoi { get; set; }
        public Nullable<double> PhutQuyDoi { get; set; }
        public Nullable<double> TongGioCong { get; set; }
        public Nullable<double> Cong { get; set; }
        public Nullable<double> NgoaiGioHC { get; set; }
        public Nullable<double> SoGioTangCa { get; set; }
        public Nullable<double> TangCa { get; set; }
        public Nullable<double> TangCaSau22H { get; set; }
    }
}
