//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_DeKhaoSat
    {
        public long IdDeKhaoSat { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> IsLapLai { get; set; }
        public Nullable<System.DateTime> Ngay1 { get; set; }
        public Nullable<int> NguoiDung1 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public Nullable<int> NguoiDung2 { get; set; }
    }
}
