//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CongThangHieuChinh
    {
        public string Nam { get; set; }
        public string Thang { get; set; }
        public string MaNV { get; set; }
        public string LoaiCong { get; set; }
        public Nullable<double> TongNC { get; set; }
        public Nullable<int> NguoiHC { get; set; }
        public Nullable<System.DateTime> NgayHC { get; set; }
    }
}
