//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_LichSuDuyet
    {
        public long IDQuyTrinh { get; set; }
        public string MaQuyTrinh { get; set; }
        public int NguoiDuyet { get; set; }
        public int SoLanDuyet { get; set; }
        public Nullable<bool> TrangThaiDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string GhiChuDuyet { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    }
}
