//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_MucKienThuc
    {
        public int MaMucKienThuc { get; set; }
        public string TenMucKienThuc { get; set; }
        public string MaKhoaDaoTao { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int NGUOIDUNG1 { get; set; }
        public Nullable<System.DateTime> NGAY1 { get; set; }
        public string MAY1 { get; set; }
        public int NGUOIDUNG2 { get; set; }
        public Nullable<System.DateTime> NGAY2 { get; set; }
        public string MAY2 { get; set; }
    }
}
