//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TTF_FACEIDEntities : DbContext
    {
        public TTF_FACEIDEntities()
            : base("name=TTF_FACEIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HT_BAOCAO> HT_BAOCAO { get; set; }
        public virtual DbSet<HT_HETHONG> HT_HETHONG { get; set; }
        public virtual DbSet<HT_NGONNGU> HT_NGONNGU { get; set; }
        public virtual DbSet<HT_NGUOIDUNG> HT_NGUOIDUNG { get; set; }
        public virtual DbSet<HT_NHOMNGUOIDUNG> HT_NHOMNGUOIDUNG { get; set; }
        public virtual DbSet<HT_NHOMQUYEN> HT_NHOMQUYEN { get; set; }
        public virtual DbSet<HT_QUYENSUDUNG> HT_QUYENSUDUNG { get; set; }
        public virtual DbSet<HT_SQL_CAU_LENH> HT_SQL_CAU_LENH { get; set; }
        public virtual DbSet<HT_TRANGTHAI> HT_TRANGTHAI { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TTF_BenhVienBHYT> TTF_BenhVienBHYT { get; set; }
        public virtual DbSet<TTF_BoNhiem> TTF_BoNhiem { get; set; }
        public virtual DbSet<TTF_BoPhan> TTF_BoPhan { get; set; }
        public virtual DbSet<TTF_CaLamViec> TTF_CaLamViec { get; set; }
        public virtual DbSet<TTF_CCwithTo> TTF_CCwithTo { get; set; }
        public virtual DbSet<TTF_ChiNhanhNganHang> TTF_ChiNhanhNganHang { get; set; }
        public virtual DbSet<TTF_ChucVu> TTF_ChucVu { get; set; }
        public virtual DbSet<TTF_CongNgay> TTF_CongNgay { get; set; }
        public virtual DbSet<TTF_CongNgayHieuChinh> TTF_CongNgayHieuChinh { get; set; }
        public virtual DbSet<TTF_CongTac> TTF_CongTac { get; set; }
        public virtual DbSet<TTF_CongTacChiTiet> TTF_CongTacChiTiet { get; set; }
        public virtual DbSet<TTF_CongTacXacNhan> TTF_CongTacXacNhan { get; set; }
        public virtual DbSet<TTF_CongThangCal> TTF_CongThangCal { get; set; }
        public virtual DbSet<TTF_CongThangCal_tmp> TTF_CongThangCal_tmp { get; set; }
        public virtual DbSet<TTF_CongThangHieuChinh> TTF_CongThangHieuChinh { get; set; }
        public virtual DbSet<TTF_CoSoLamViec> TTF_CoSoLamViec { get; set; }
        public virtual DbSet<TTF_CostCenter> TTF_CostCenter { get; set; }
        public virtual DbSet<TTF_DanToc> TTF_DanToc { get; set; }
        public virtual DbSet<TTF_DLVT_CaDem> TTF_DLVT_CaDem { get; set; }
        public virtual DbSet<TTF_DuyetTangCaPM> TTF_DuyetTangCaPM { get; set; }
        public virtual DbSet<TTF_DuyetTangCaPMDacBiet> TTF_DuyetTangCaPMDacBiet { get; set; }
        public virtual DbSet<TTF_Employees> TTF_Employees { get; set; }
        public virtual DbSet<TTF_EvenLog> TTF_EvenLog { get; set; }
        public virtual DbSet<TTF_FormatContractType> TTF_FormatContractType { get; set; }
        public virtual DbSet<TTF_Import> TTF_Import { get; set; }
        public virtual DbSet<TTF_Khoi> TTF_Khoi { get; set; }
        public virtual DbSet<TTF_KiemTra> TTF_KiemTra { get; set; }
        public virtual DbSet<TTF_KyCongNguoiDung> TTF_KyCongNguoiDung { get; set; }
        public virtual DbSet<TTF_LichSuDuyet> TTF_LichSuDuyet { get; set; }
        public virtual DbSet<TTF_LoaiCong> TTF_LoaiCong { get; set; }
        public virtual DbSet<TTF_LoaiLaoDong> TTF_LoaiLaoDong { get; set; }
        public virtual DbSet<TTF_LoaiNghiPhep> TTF_LoaiNghiPhep { get; set; }
        public virtual DbSet<TTF_LoaiTangCa> TTF_LoaiTangCa { get; set; }
        public virtual DbSet<TTF_LogChangeEmployees> TTF_LogChangeEmployees { get; set; }
        public virtual DbSet<TTF_Mails> TTF_Mails { get; set; }
        public virtual DbSet<TTF_MaTrixDuyetCongTac> TTF_MaTrixDuyetCongTac { get; set; }
        public virtual DbSet<TTF_MaTrixDuyetNghiPhep> TTF_MaTrixDuyetNghiPhep { get; set; }
        public virtual DbSet<TTF_MaTrixDuyetTangCa> TTF_MaTrixDuyetTangCa { get; set; }
        public virtual DbSet<TTF_MucKienThuc> TTF_MucKienThuc { get; set; }
        public virtual DbSet<TTF_NganHang> TTF_NganHang { get; set; }
        public virtual DbSet<TTF_NgayLe> TTF_NgayLe { get; set; }
        public virtual DbSet<TTF_NghiBu> TTF_NghiBu { get; set; }
        public virtual DbSet<TTF_NghiBuChiTiet> TTF_NghiBuChiTiet { get; set; }
        public virtual DbSet<TTF_NghiPhep> TTF_NghiPhep { get; set; }
        public virtual DbSet<TTF_NghiPhepChiTiet> TTF_NghiPhepChiTiet { get; set; }
        public virtual DbSet<TTF_NhanSu> TTF_NhanSu { get; set; }
        public virtual DbSet<TTF_NhanSu_CongNgayPhepDacBiet> TTF_NhanSu_CongNgayPhepDacBiet { get; set; }
        public virtual DbSet<TTF_NhanSu_PhepThang> TTF_NhanSu_PhepThang { get; set; }
        public virtual DbSet<TTF_NhanSuCaLamViec> TTF_NhanSuCaLamViec { get; set; }
        public virtual DbSet<TTF_NhanSuDacBiet> TTF_NhanSuDacBiet { get; set; }
        public virtual DbSet<TTF_NhatkyLoi> TTF_NhatkyLoi { get; set; }
        public virtual DbSet<TTF_NhomCauHoi> TTF_NhomCauHoi { get; set; }
        public virtual DbSet<TTF_PhamVi> TTF_PhamVi { get; set; }
        public virtual DbSet<TTF_PhongBan_PhanXuong> TTF_PhongBan_PhanXuong { get; set; }
        public virtual DbSet<TTF_QuocTich> TTF_QuocTich { get; set; }
        public virtual DbSet<TTF_QuyTrinh> TTF_QuyTrinh { get; set; }
        public virtual DbSet<TTF_SHIFTS> TTF_SHIFTS { get; set; }
        public virtual DbSet<TTF_TangCa> TTF_TangCa { get; set; }
        public virtual DbSet<TTF_TangCaChiTiet> TTF_TangCaChiTiet { get; set; }
        public virtual DbSet<TTF_TangCatemp> TTF_TangCatemp { get; set; }
        public virtual DbSet<TTF_TangCuong> TTF_TangCuong { get; set; }
        public virtual DbSet<TTF_TimekeepingPeriod> TTF_TimekeepingPeriod { get; set; }
        public virtual DbSet<TTF_TinhTrang> TTF_TinhTrang { get; set; }
        public virtual DbSet<TTF_ToChuyen> TTF_ToChuyen { get; set; }
        public virtual DbSet<TTF_TonGiao> TTF_TonGiao { get; set; }
        public virtual DbSet<TTF_TrangThaiDuyet> TTF_TrangThaiDuyet { get; set; }
        public virtual DbSet<TTF_TrinhDoHocVan> TTF_TrinhDoHocVan { get; set; }
        public virtual DbSet<TTF_XacNhanCong> TTF_XacNhanCong { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<HT_NHATKY> HT_NHATKY { get; set; }
        public virtual DbSet<V_Users> V_Users { get; set; }
        public virtual DbSet<v_capquanly> v_capquanly { get; set; }
        public virtual DbSet<TTF_ChangeLogs> TTF_ChangeLogs { get; set; }
        public virtual DbSet<v_CCwithTo> v_CCwithTo { get; set; }
        public virtual DbSet<TTF_BaiThiLuu> TTF_BaiThiLuu { get; set; }
        public virtual DbSet<TTF_CauHoi> TTF_CauHoi { get; set; }
        public virtual DbSet<TTF_CauHoi_DapAn> TTF_CauHoi_DapAn { get; set; }
        public virtual DbSet<TTF_DeKhaoSat> TTF_DeKhaoSat { get; set; }
        public virtual DbSet<TTF_DeKhaoSat_CauHoi> TTF_DeKhaoSat_CauHoi { get; set; }
        public virtual DbSet<TTF_LoaiCauHoi> TTF_LoaiCauHoi { get; set; }
        public virtual DbSet<TTF_NhanSu_DeKhaoSat_TraLoi> TTF_NhanSu_DeKhaoSat_TraLoi { get; set; }
    
        public virtual ObjectResult<TTF_GET_ALL_NhanSu_Result> TTF_GET_ALL_NhanSu(string maChucVu, string maPhongBan, string maNV, string maTinhTrang, string del)
        {
            var maChucVuParameter = maChucVu != null ?
                new ObjectParameter("MaChucVu", maChucVu) :
                new ObjectParameter("MaChucVu", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maTinhTrangParameter = maTinhTrang != null ?
                new ObjectParameter("MaTinhTrang", maTinhTrang) :
                new ObjectParameter("MaTinhTrang", typeof(string));
    
            var delParameter = del != null ?
                new ObjectParameter("Del", del) :
                new ObjectParameter("Del", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTF_GET_ALL_NhanSu_Result>("TTF_GET_ALL_NhanSu", maChucVuParameter, maPhongBanParameter, maNVParameter, maTinhTrangParameter, delParameter);
        }
    
        public virtual ObjectResult<TTF_InTheTen_Result> TTF_InTheTen(string maPhongBan, string chucVu, string maNV, string tuNgay, string denNgay)
        {
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTF_InTheTen_Result>("TTF_InTheTen", maPhongBanParameter, chucVuParameter, maNVParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Proc_QuaTrinhNghiPhep_Result> Proc_QuaTrinhNghiPhep(Nullable<int> nguoiTao, string tuNgay, string denNgay)
        {
            var nguoiTaoParameter = nguoiTao.HasValue ?
                new ObjectParameter("NguoiTao", nguoiTao) :
                new ObjectParameter("NguoiTao", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_QuaTrinhNghiPhep_Result>("Proc_QuaTrinhNghiPhep", nguoiTaoParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<TTF_DuyetNghiPhep_Result> TTF_DuyetNghiPhep(Nullable<int> nguoiDuyet, string tuNgay, string denNgay, string maNV, string maPhongBan)
        {
            var nguoiDuyetParameter = nguoiDuyet.HasValue ?
                new ObjectParameter("NguoiDuyet", nguoiDuyet) :
                new ObjectParameter("NguoiDuyet", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTF_DuyetNghiPhep_Result>("TTF_DuyetNghiPhep", nguoiDuyetParameter, tuNgayParameter, denNgayParameter, maNVParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_GetDanhSachDuyetNghiPhep_Result> Proc_GetDanhSachDuyetNghiPhep(Nullable<int> nguoiDuyet, string tuNgay, string denNgay, string maNV, string maPhongBan)
        {
            var nguoiDuyetParameter = nguoiDuyet.HasValue ?
                new ObjectParameter("NguoiDuyet", nguoiDuyet) :
                new ObjectParameter("NguoiDuyet", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetDanhSachDuyetNghiPhep_Result>("Proc_GetDanhSachDuyetNghiPhep", nguoiDuyetParameter, tuNgayParameter, denNgayParameter, maNVParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_QuanLyNghiPhep_Result> Proc_QuanLyNghiPhep(string tuNgay, string denNgay, string maNV, string maPhongBan, string maLoaiNghiPhep)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            var maLoaiNghiPhepParameter = maLoaiNghiPhep != null ?
                new ObjectParameter("MaLoaiNghiPhep", maLoaiNghiPhep) :
                new ObjectParameter("MaLoaiNghiPhep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_QuanLyNghiPhep_Result>("Proc_QuanLyNghiPhep", tuNgayParameter, denNgayParameter, maNVParameter, maPhongBanParameter, maLoaiNghiPhepParameter);
        }
    
        public virtual ObjectResult<Proc_QuanLyXacNhanCong_Result> Proc_QuanLyXacNhanCong(string tuNgay, string denNgay, string maPhongBan, string hoVaTen, Nullable<bool> xacNhanCong)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("maPhongBan", maPhongBan) :
                new ObjectParameter("maPhongBan", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("hoVaTen", hoVaTen) :
                new ObjectParameter("hoVaTen", typeof(string));
    
            var xacNhanCongParameter = xacNhanCong.HasValue ?
                new ObjectParameter("xacNhanCong", xacNhanCong) :
                new ObjectParameter("xacNhanCong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_QuanLyXacNhanCong_Result>("Proc_QuanLyXacNhanCong", tuNgayParameter, denNgayParameter, maPhongBanParameter, hoVaTenParameter, xacNhanCongParameter);
        }
    
        public virtual ObjectResult<Proc_QuaTrinhXacNhanCong_Result> Proc_QuaTrinhXacNhanCong(Nullable<int> nguoiTao, string tuNgay, string denNgay)
        {
            var nguoiTaoParameter = nguoiTao.HasValue ?
                new ObjectParameter("NguoiTao", nguoiTao) :
                new ObjectParameter("NguoiTao", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_QuaTrinhXacNhanCong_Result>("Proc_QuaTrinhXacNhanCong", nguoiTaoParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Proc_GetDuyetXacNhanCong_Result> Proc_GetDuyetXacNhanCong(Nullable<int> nguoiDuyet, string tuNgay, string denNgay, string phongBan, string hoVaTen, Nullable<bool> xacNhanCong)
        {
            var nguoiDuyetParameter = nguoiDuyet.HasValue ?
                new ObjectParameter("nguoiDuyet", nguoiDuyet) :
                new ObjectParameter("nguoiDuyet", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            var phongBanParameter = phongBan != null ?
                new ObjectParameter("phongBan", phongBan) :
                new ObjectParameter("phongBan", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("hoVaTen", hoVaTen) :
                new ObjectParameter("hoVaTen", typeof(string));
    
            var xacNhanCongParameter = xacNhanCong.HasValue ?
                new ObjectParameter("xacNhanCong", xacNhanCong) :
                new ObjectParameter("xacNhanCong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetDuyetXacNhanCong_Result>("Proc_GetDuyetXacNhanCong", nguoiDuyetParameter, tuNgayParameter, denNgayParameter, phongBanParameter, hoVaTenParameter, xacNhanCongParameter);
        }
    
        public virtual ObjectResult<Proc_BaoCaoXacNhanCong_Result> Proc_BaoCaoXacNhanCong(string tuNgay, string denNgay, string maPhongBan, Nullable<int> soLan, Nullable<bool> xacNhanCong)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("maPhongBan", maPhongBan) :
                new ObjectParameter("maPhongBan", typeof(string));
    
            var soLanParameter = soLan.HasValue ?
                new ObjectParameter("soLan", soLan) :
                new ObjectParameter("soLan", typeof(int));
    
            var xacNhanCongParameter = xacNhanCong.HasValue ?
                new ObjectParameter("XacNhanCong", xacNhanCong) :
                new ObjectParameter("XacNhanCong", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_BaoCaoXacNhanCong_Result>("Proc_BaoCaoXacNhanCong", tuNgayParameter, denNgayParameter, maPhongBanParameter, soLanParameter, xacNhanCongParameter);
        }
    
        public virtual ObjectResult<TTF_KiemTraThoiGianTangCaTRung_Result> TTF_KiemTraThoiGianTangCaTRung(Nullable<int> nhanSu, Nullable<System.DateTime> ngay, Nullable<System.TimeSpan> tuGio, Nullable<System.TimeSpan> denGio)
        {
            var nhanSuParameter = nhanSu.HasValue ?
                new ObjectParameter("NhanSu", nhanSu) :
                new ObjectParameter("NhanSu", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            var tuGioParameter = tuGio.HasValue ?
                new ObjectParameter("TuGio", tuGio) :
                new ObjectParameter("TuGio", typeof(System.TimeSpan));
    
            var denGioParameter = denGio.HasValue ?
                new ObjectParameter("DenGio", denGio) :
                new ObjectParameter("DenGio", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTF_KiemTraThoiGianTangCaTRung_Result>("TTF_KiemTraThoiGianTangCaTRung", nhanSuParameter, ngayParameter, tuGioParameter, denGioParameter);
        }
    
        public virtual ObjectResult<Proc_TangCaCuaBan_Result> Proc_TangCaCuaBan(Nullable<int> nguoiTao, string tuNgay, string denNgay)
        {
            var nguoiTaoParameter = nguoiTao.HasValue ?
                new ObjectParameter("nguoiTao", nguoiTao) :
                new ObjectParameter("nguoiTao", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_TangCaCuaBan_Result>("Proc_TangCaCuaBan", nguoiTaoParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Proc_DuyetTangCa_Result> Proc_DuyetTangCa(string tuNgay, string denNgay, string maPhongBan, string hoVaTen, Nullable<int> nguoiDuyet)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("maPhongBan", maPhongBan) :
                new ObjectParameter("maPhongBan", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("hoVaTen", hoVaTen) :
                new ObjectParameter("hoVaTen", typeof(string));
    
            var nguoiDuyetParameter = nguoiDuyet.HasValue ?
                new ObjectParameter("nguoiDuyet", nguoiDuyet) :
                new ObjectParameter("nguoiDuyet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_DuyetTangCa_Result>("Proc_DuyetTangCa", tuNgayParameter, denNgayParameter, maPhongBanParameter, hoVaTenParameter, nguoiDuyetParameter);
        }
    
        public virtual ObjectResult<Proc_QuanLyTangCa_Result> Proc_QuanLyTangCa(string tuNgay, string denNgay, string maPhongBan, string hoVaTen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("maPhongBan", maPhongBan) :
                new ObjectParameter("maPhongBan", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("hoVaTen", hoVaTen) :
                new ObjectParameter("hoVaTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_QuanLyTangCa_Result>("Proc_QuanLyTangCa", tuNgayParameter, denNgayParameter, maPhongBanParameter, hoVaTenParameter);
        }
    
        public virtual int TTF_ThongTinTangCaChiTiet(string tuNgay, string denNgay, string maPhongBan, string hoVaTen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TTF_ThongTinTangCaChiTiet", tuNgayParameter, denNgayParameter, maPhongBanParameter, hoVaTenParameter);
        }
    
        public virtual ObjectResult<Proc_ThongTinTangCaChiTiet_Result> Proc_ThongTinTangCaChiTiet(string tuNgay, string denNgay, string maPhongBan, string hoVaTen)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ThongTinTangCaChiTiet_Result>("Proc_ThongTinTangCaChiTiet", tuNgayParameter, denNgayParameter, maPhongBanParameter, hoVaTenParameter);
        }
    
        public virtual ObjectResult<Proc_NhanSuForCong_Result> Proc_NhanSuForCong(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_NhanSuForCong_Result>("Proc_NhanSuForCong", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_CongBinhDuong_Result> Proc_CongBinhDuong(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_CongBinhDuong_Result>("Proc_CongBinhDuong", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_CongCaDem_Result> Proc_CongCaDem(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_CongCaDem_Result>("Proc_CongCaDem", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_CongThuDuc_Result> Proc_CongThuDuc(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_CongThuDuc_Result>("Proc_CongThuDuc", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<ttf_CongKhuonMat_Result> ttf_CongKhuonMat(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ttf_CongKhuonMat_Result>("ttf_CongKhuonMat", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<Proc_CanLamViecCongTrinh_Result> Proc_CanLamViecCongTrinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_CanLamViecCongTrinh_Result>("Proc_CanLamViecCongTrinh");
        }
    
        public virtual ObjectResult<Pro_CongTac_Result> Pro_CongTac(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_CongTac_Result>("Pro_CongTac", tuNgayParameter, denNgayParameter);
        }
    
        public virtual int CheckNgayThuocKyCongNao(string ngay, ObjectParameter year, ObjectParameter month)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckNgayThuocKyCongNao", ngayParameter, year, month);
        }
    
        public virtual ObjectResult<Proc_TangCaChiTiet_Result> Proc_TangCaChiTiet(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_TangCaChiTiet_Result>("Proc_TangCaChiTiet", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_XacNhanCong_Result> Proc_XacNhanCong(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_XacNhanCong_Result>("Proc_XacNhanCong", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_CongNgayHieuChinh_Result> Proc_CongNgayHieuChinh(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_CongNgayHieuChinh_Result>("Proc_CongNgayHieuChinh", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<Proc_NhanSuCaLamViec_Result> Proc_NhanSuCaLamViec(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string maNV, string hoVaTen, string maPhongBan)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maPhongBanParameter = maPhongBan != null ?
                new ObjectParameter("MaPhongBan", maPhongBan) :
                new ObjectParameter("MaPhongBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_NhanSuCaLamViec_Result>("Proc_NhanSuCaLamViec", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maPhongBanParameter);
        }
    
        public virtual ObjectResult<TTF_KiemTraThoiGianTangCaTrungEdit_Result> TTF_KiemTraThoiGianTangCaTrungEdit(Nullable<int> nhanSu, Nullable<System.DateTime> ngay, Nullable<System.TimeSpan> tuGio, Nullable<System.TimeSpan> denGio, Nullable<int> iDTangCa)
        {
            var nhanSuParameter = nhanSu.HasValue ?
                new ObjectParameter("NhanSu", nhanSu) :
                new ObjectParameter("NhanSu", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            var tuGioParameter = tuGio.HasValue ?
                new ObjectParameter("TuGio", tuGio) :
                new ObjectParameter("TuGio", typeof(System.TimeSpan));
    
            var denGioParameter = denGio.HasValue ?
                new ObjectParameter("DenGio", denGio) :
                new ObjectParameter("DenGio", typeof(System.TimeSpan));
    
            var iDTangCaParameter = iDTangCa.HasValue ?
                new ObjectParameter("IDTangCa", iDTangCa) :
                new ObjectParameter("IDTangCa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTF_KiemTraThoiGianTangCaTrungEdit_Result>("TTF_KiemTraThoiGianTangCaTrungEdit", nhanSuParameter, ngayParameter, tuGioParameter, denGioParameter, iDTangCaParameter);
        }
    
        public virtual ObjectResult<proc_ChamCongKhuonMat_Result> proc_ChamCongKhuonMat(string tuNgay, string denNgay, string maNV, string hoVaTen, string maDuAn)
        {
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("HoVaTen", hoVaTen) :
                new ObjectParameter("HoVaTen", typeof(string));
    
            var maDuAnParameter = maDuAn != null ?
                new ObjectParameter("MaDuAn", maDuAn) :
                new ObjectParameter("MaDuAn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ChamCongKhuonMat_Result>("proc_ChamCongKhuonMat", tuNgayParameter, denNgayParameter, maNVParameter, hoVaTenParameter, maDuAnParameter);
        }
    
        public virtual ObjectResult<Proc_ChamCongKhongThanh_Result> Proc_ChamCongKhongThanh(Nullable<int> nguoiDung, string tuNgay, string denNgay, string hoVaTen)
        {
            var nguoiDungParameter = nguoiDung.HasValue ?
                new ObjectParameter("nguoiDung", nguoiDung) :
                new ObjectParameter("nguoiDung", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("hoVaTen", hoVaTen) :
                new ObjectParameter("hoVaTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ChamCongKhongThanh_Result>("Proc_ChamCongKhongThanh", nguoiDungParameter, tuNgayParameter, denNgayParameter, hoVaTenParameter);
        }
    
        public virtual ObjectResult<Proc_GetDuyetChamCongKhongThanh_Result> Proc_GetDuyetChamCongKhongThanh(Nullable<int> nguoiDuyet, string tuNgay, string denNgay, string phongBan, string hoVaTen)
        {
            var nguoiDuyetParameter = nguoiDuyet.HasValue ?
                new ObjectParameter("nguoiDuyet", nguoiDuyet) :
                new ObjectParameter("nguoiDuyet", typeof(int));
    
            var tuNgayParameter = tuNgay != null ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(string));
    
            var denNgayParameter = denNgay != null ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(string));
    
            var phongBanParameter = phongBan != null ?
                new ObjectParameter("phongBan", phongBan) :
                new ObjectParameter("phongBan", typeof(string));
    
            var hoVaTenParameter = hoVaTen != null ?
                new ObjectParameter("hoVaTen", hoVaTen) :
                new ObjectParameter("hoVaTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetDuyetChamCongKhongThanh_Result>("Proc_GetDuyetChamCongKhongThanh", nguoiDuyetParameter, tuNgayParameter, denNgayParameter, phongBanParameter, hoVaTenParameter);
        }
    }
}
