//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CongTacXacNhan
    {
        public decimal ID { get; set; }
        public Nullable<long> IDCongTac { get; set; }
        public string NoiDi { get; set; }
        public string NoiDen { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string PhuongTien { get; set; }
        public string NoiDungCongTac { get; set; }
        public string ThoiGian { get; set; }
    }
}
