//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_TangCa
    {
        public long IDTangCa { get; set; }
        public Nullable<System.DateTime> NgayTangCa { get; set; }
        public Nullable<System.TimeSpan> GioBatDau { get; set; }
        public Nullable<System.TimeSpan> GioKetThuc { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<int> IDNguoiDuyetKeTiep { get; set; }
        public string MaPhong_PhanXuong { get; set; }
        public string MaTrangThaiDuyet { get; set; }
        public Nullable<bool> DotXuat { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<int> NguoiThayDoiLanCuoi { get; set; }
        public Nullable<System.DateTime> NgayThayDoiLanCuoi { get; set; }
        public Nullable<bool> Block { get; set; }
        public Nullable<System.DateTime> NgayBlock { get; set; }
        public Nullable<int> NguoiDeXetDuyet { get; set; }
        public Nullable<int> NguoiTuChoi { get; set; }
        public Nullable<System.DateTime> NgayTuChoi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NguoiKiemTra { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public Nullable<int> MaKiemTra { get; set; }
        public string GhiChuKiemTra { get; set; }
        public bool DuAn { get; set; }
        public string MaDuAn { get; set; }
        public Nullable<bool> CongTac { get; set; }
    }
}
