//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_LoaiNghiPhep
    {
        public string MaLoaiNghiPhep { get; set; }
        public string TenLoaiNghiPhep { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
