//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_BaiThiLuu
    {
        public long IdBaiThiLuu { get; set; }
        public Nullable<long> NhanSu { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<System.DateTime> Ngay1 { get; set; }
        public Nullable<int> NguoiDung1 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public Nullable<int> NguoiDung2 { get; set; }
        public string IpMayTinh { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public long IdDeKhaoSat { get; set; }
    }
}
