//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_DuAn
    {
        public string MaDuAn { get; set; }
        public string TenDuAn { get; set; }
        public string MaLoaiDuAn { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Del { get; set; }
        public string MaNV { get; set; }
    }
}
