//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_NghiBu
    {
        public string MaNV { get; set; }
        public System.DateTime NgayPhatSinh { get; set; }
        public long IDTangCa { get; set; }
        public Nullable<double> SoPhut { get; set; }
        public Nullable<double> SoPhutConLai { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public Nullable<System.DateTime> NgayHetHieuLuc { get; set; }
        public Nullable<bool> TCDaHuy { get; set; }
        public Nullable<int> ThayDoiLanCuoiBoi { get; set; }
        public Nullable<System.DateTime> ThayDoiLanCuoiLuc { get; set; }
    }
}
