//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_BoNhiem
    {
        public long IDBoNhiem { get; set; }
        public Nullable<long> NhanSu { get; set; }
        public string SoQD { get; set; }
        public string MaChucVu { get; set; }
        public string MaPhong_PhanXuong { get; set; }
        public string MaChucVuCu { get; set; }
        public string MaPhongBanCu { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<bool> Del { get; set; }
        public string NguoiDeNghi { get; set; }
        public Nullable<bool> ISBoNhiem { get; set; }
    }
}
