//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_Import
    {
        public string Table_Name { get; set; }
        public string Column_Name { get; set; }
        public string Data_type { get; set; }
        public string Scaption { get; set; }
        public string Table_Link { get; set; }
        public string Table_Group { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
