//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_DLVT_CaDem
    {
        public string UID { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
    }
}
