//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CongThangCal_tmp
    {
        public string MaNV { get; set; }
        public string Nam { get; set; }
        public string Thang { get; set; }
        public string MaLoaiCong { get; set; }
        public string Cot1 { get; set; }
        public string Cot2 { get; set; }
        public string Cot3 { get; set; }
        public string Cot4 { get; set; }
        public string Cot5 { get; set; }
        public string Cot6 { get; set; }
        public string Cot7 { get; set; }
        public string Cot8 { get; set; }
        public string Cot9 { get; set; }
        public string Cot10 { get; set; }
        public string Cot11 { get; set; }
        public string Cot12 { get; set; }
        public string Cot13 { get; set; }
        public string Cot14 { get; set; }
        public string Cot15 { get; set; }
        public string Cot16 { get; set; }
        public string Cot17 { get; set; }
        public string Cot18 { get; set; }
        public string Cot19 { get; set; }
        public string Cot20 { get; set; }
        public string Cot21 { get; set; }
        public string Cot22 { get; set; }
        public string Cot23 { get; set; }
        public string Cot24 { get; set; }
        public string Cot25 { get; set; }
        public string Cot26 { get; set; }
        public string Cot27 { get; set; }
        public string Cot28 { get; set; }
        public string Cot29 { get; set; }
        public string Cot30 { get; set; }
        public string Cot31 { get; set; }
        public Nullable<double> SoNgayPhepConLai { get; set; }
        public Nullable<double> NgayCongChuan { get; set; }
        public Nullable<double> DLCong { get; set; }
        public Nullable<double> SoNgayCT_NB { get; set; }
        public Nullable<double> TongNC { get; set; }
        public Nullable<double> TongNCHC { get; set; }
        public Nullable<double> TCThuong { get; set; }
        public Nullable<double> TCSau22H { get; set; }
        public Nullable<double> TCCN { get; set; }
        public Nullable<double> TCCNSau22H { get; set; }
        public Nullable<double> TCLe { get; set; }
        public Nullable<double> PhepNam_Le_TNLD { get; set; }
        public Nullable<double> SoNgayLamDem { get; set; }
        public Nullable<double> ChuyenCan { get; set; }
        public Nullable<double> XNC5LThang { get; set; }
        public Nullable<double> NghiKhongPhep { get; set; }
        public Nullable<int> LoaiCongOrder { get; set; }
        public Nullable<int> STT { get; set; }
    }
}
