//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_BoPhan
    {
        public string MaBoPhan { get; set; }
        public string TenBoPhan { get; set; }
        public string MaPhong_PhanXuong { get; set; }
        public Nullable<bool> Del { get; set; }
    }
}
