//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_LogChangeEmployees
    {
        public int NhanSu { get; set; }
        public System.DateTime NgayThayDoi { get; set; }
        public string NoiDungThayDoi { get; set; }
        public Nullable<int> NguoiDungThayDoi { get; set; }
    }
}
