//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_TimekeepingPeriod
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangedOn { get; set; }
        public Nullable<bool> EmployeeStatus { get; set; }
    }
}
