//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_EvenLog
    {
        public string EmployeeCode { get; set; }
        public string ShiftName { get; set; }
        public string DirectionAndStatus { get; set; }
        public System.DateTime Time { get; set; }
        public string TimeZone { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Construction { get; set; }
        public string Remark { get; set; }
        public string EmployeeID { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiDungTao { get; set; }
        public Nullable<bool> CongTac { get; set; }
        public Nullable<int> NguoiCapNhatCongTac { get; set; }
        public Nullable<System.DateTime> NgayCapNhatCongTac { get; set; }
        public Nullable<int> NguoiHuy { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
    }
}
