//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_ChucVu
    {
        public string MaChucVu { get; set; }
        public string TenChucVu { get; set; }
        public string PhanLoai { get; set; }
        public Nullable<bool> Loai { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<int> LoaiThe { get; set; }
    }
}
