//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_KyCongNguoiDung
    {
        public long Id { get; set; }
        public int Nam { get; set; }
        public int Thang { get; set; }
        public System.DateTime TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<bool> Dong { get; set; }
        public Nullable<int> NguoiDungDong { get; set; }
        public Nullable<System.DateTime> NgayDong { get; set; }
        public Nullable<int> NguoiDungMo { get; set; }
        public Nullable<System.DateTime> NgayMo { get; set; }
    }
}
