//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_TangCuong
    {
        public int NhanSu { get; set; }
        public System.DateTime Ngay { get; set; }
        public string MaPhong_PhanXuong { get; set; }
        public Nullable<int> NguoiDung1 { get; set; }
        public string May1 { get; set; }
        public long ID { get; set; }
        public string ToChuyen { get; set; }
        public Nullable<System.TimeSpan> TuGio { get; set; }
        public Nullable<System.TimeSpan> DenGio { get; set; }
    }
}
