//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_NhanSu
    {
        public int NhanSu { get; set; }
        public string MaNV { get; set; }
        public string MaChamCong { get; set; }
        public string MaLuuHoSo { get; set; }
        public string HoVaTen { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string SoCMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string MaPhong_PhanXuong { get; set; }
        public string MaChucVu { get; set; }
        public Nullable<System.DateTime> NgayBoNhiem { get; set; }
        public string MaCoSo { get; set; }
        public Nullable<System.DateTime> NgayVaoCongTy { get; set; }
        public string ChuyenNganh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> NgayNghiViec { get; set; }
        public string MaTinhTrang { get; set; }
        public string Images { get; set; }
        public string NguoiDung1 { get; set; }
        public Nullable<System.DateTime> Ngay1 { get; set; }
        public string NguoiDung2 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public string MaCaLamViec { get; set; }
        public string MaDanToc { get; set; }
        public string MaTonGiao { get; set; }
        public string MaQuocTich { get; set; }
        public string MaTrinhDoHocVan { get; set; }
        public string SoTaiKhoanNganHang { get; set; }
        public string MaNganHang { get; set; }
        public string MaChiNhanhNganHang { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<int> NgayCongChuan { get; set; }
        public string MailCongTy { get; set; }
        public string So3CX { get; set; }
        public string Skype { get; set; }
        public string Dropbox { get; set; }
        public string SoDTNguoiThan { get; set; }
        public string SoBHXH { get; set; }
        public string MaBV { get; set; }
        public Nullable<System.DateTime> TGThuViecTuNgay { get; set; }
        public Nullable<System.DateTime> TGThuViecDenNgay { get; set; }
        public string NguyenQuan { get; set; }
        public string DCThuongTru { get; set; }
        public string DCCuTru { get; set; }
        public string DCHoKhau { get; set; }
        public Nullable<bool> IsKetHon { get; set; }
        public Nullable<int> IDCapQuanLyTrucTiep { get; set; }
        public Nullable<double> SoNgayPhepConLai { get; set; }
        public string MaKhoi { get; set; }
        public string MaBoPhan { get; set; }
        public string MaLoaiLaoDong { get; set; }
        public string MaToChuyen { get; set; }
        public string LoaiLaoDongTangCa { get; set; }
        public Nullable<int> SoNgayThuViec { get; set; }
        public Nullable<System.DateTime> NgayDel { get; set; }
        public Nullable<int> NguoiDel { get; set; }
        public Nullable<bool> KhongTinhTC { get; set; }
        public string MaChamCongCu { get; set; }
        public string MaNVCu { get; set; }
        public Nullable<bool> ChamCongKM { get; set; }
        public Nullable<System.DateTime> DocHaiTuNgay { get; set; }
        public Nullable<System.DateTime> DocHaiDenNgay { get; set; }
    }
}
