//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_NhanSu_DeKhaoSat_TraLoi
    {
        public long IdBaiThiLuu { get; set; }
        public long IdCauHoi { get; set; }
        public Nullable<long> IdDapAn { get; set; }
        public string NoiDungTraLoi { get; set; }
        public Nullable<bool> IsDung { get; set; }
    }
}
