//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CongTacChiTiet
    {
        public long IDCongTac { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<System.TimeSpan> TuGio { get; set; }
        public Nullable<System.TimeSpan> DenGio { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<int> NguoiDel { get; set; }
        public Nullable<System.DateTime> NgayDel { get; set; }
    }
}
