//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CongNgayHieuChinh
    {
        public System.DateTime Date { get; set; }
        public string MaNV { get; set; }
        public string Cong { get; set; }
        public string TangCa { get; set; }
        public string TangCaSau22H { get; set; }
        public string InTime { get; set; }
        public string OutDate { get; set; }
        public string OutTime { get; set; }
        public Nullable<int> NguoiHC { get; set; }
        public Nullable<System.DateTime> NgayHC { get; set; }
    }
}
