//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_Mails
    {
        public string MaDuAn { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<bool> TinhCong { get; set; }
        public string MaCaLamViec { get; set; }
    }
}
