//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_NhanSuDacBiet
    {
        public string MaNV { get; set; }
        public Nullable<int> MaLoaiDacBiet { get; set; }
        public Nullable<bool> DuocDiTre { get; set; }
        public Nullable<int> SoPhut { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.TimeSpan> CanGioRa { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
    }
}
