//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CaLamViec
    {
        public string MaCaLamViec { get; set; }
        public string TenCaLamViec { get; set; }
        public Nullable<System.TimeSpan> GioBacDau { get; set; }
        public Nullable<System.TimeSpan> GioKetThuc { get; set; }
        public Nullable<System.TimeSpan> GioTinhTangCa { get; set; }
        public Nullable<System.TimeSpan> GioRaGiuaCa { get; set; }
        public Nullable<System.TimeSpan> GioVaoGiuaCa { get; set; }
        public string LoaiCa { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoPhutDiTre { get; set; }
        public Nullable<double> TongGioCong { get; set; }
    }
}
