//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_CongTac
    {
        public long IDCongTac { get; set; }
        public Nullable<int> NhanSu { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.TimeSpan> TuGio { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<System.TimeSpan> DenGio { get; set; }
        public string NoiDungCongTac { get; set; }
        public string GhiChu { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string MayTao { get; set; }
        public string MaTrangThaiDuyet { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<int> IDNguoiDuyetKeTiep { get; set; }
        public Nullable<bool> Block { get; set; }
        public Nullable<System.DateTime> NgayBlock { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<int> NguoiThayDoiLanCuoi { get; set; }
        public Nullable<System.DateTime> NgayThayDoiLanCuoi { get; set; }
        public string NoiCongTac { get; set; }
        public Nullable<bool> DuAn { get; set; }
        public Nullable<decimal> TongPhiCongTac { get; set; }
        public string MaDuAn { get; set; }
        public Nullable<int> NguoiTuChoi { get; set; }
        public Nullable<System.DateTime> NgayTuChoi { get; set; }
    }
}
