//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_NhanSuCaLamViec
    {
        public int NhanSu { get; set; }
        public System.DateTime NgayCong { get; set; }
        public System.TimeSpan GioVao { get; set; }
        public System.TimeSpan GioRa { get; set; }
        public string GhiChu { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> NgayImport { get; set; }
        public Nullable<int> NguoiDungImport { get; set; }
    }
}
