//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTF_Employees
    {
        public string EmployeeCode { get; set; }
        public string FistName { get; set; }
        public string LastName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Zip_PostalCode { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string EmployeeID { get; set; }
        public string ContructionsID { get; set; }
        public string ContractType { get; set; }
        public Nullable<System.DateTime> NgayImport { get; set; }
        public Nullable<System.DateTime> NgayEdit { get; set; }
        public string Position { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Del { get; set; }
        public string Gender { get; set; }
        public string Passport_Id { get; set; }
    }
}
