//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CCwithTo
    {
        public string Type { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string MailCongTy_To { get; set; }
        public string MailCongTy_CC { get; set; }
    }
}
