//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTFPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Users
    {
        public int NGUOIDUNG { get; set; }
        public string TAIKHOAN { get; set; }
        public string MailCongTy { get; set; }
        public string MaPhong_PhanXuong { get; set; }
        public Nullable<int> NHOMNGUOIDUNG { get; set; }
        public Nullable<int> NhanSu { get; set; }
        public string HoVaTen { get; set; }
        public string Images { get; set; }
        public string MaNV { get; set; }
        public string TenPhong { get; set; }
    }
}
